const TipoEvento = {
  USUARIO_CREADO: 'USUARIO_CREADO',
  LOGIN_CREDENCIALES: 'LOGIN_CREDENCIALES',
  LOGIN_GOOGLE: 'LOGIN_GOOGLE',
  USUARIO_BLOQUEADO: 'USUARIO_BLOQUEADO'
}

module.exports = TipoEvento
